modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[26,)" #mandatory (26 is current forge version)
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="practicaltools" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.14.4-1.4" #mandatory
 # A display name for the mod
displayName="Practical Tools" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/astradamus/PracticalTools/" #optional
# A text field displayed in the mod UI
authors="astradamus" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds three tools--the excavator, the hammer, and the greataxe. These are 3x3 versions of the shovel, pickaxe, and axe, respectively. The greataxe, when used on a tree, will fell the entire tree at once.

Each tool comes in iron, gold, and diamond variants. Their recipes match their vanilla equivalents, but use blocks instead of ingots for both crafting and repair.

The greataxe boasts a more accurate tree detection method than I've seen in previous mods, and should never leave floating treetops.

Inspired by the many mods that implement these tools in previous versions of MC, my goal was to make 1.14 a little less vanilla so mod-addicts like myself can finally explore the new features added since 1.12!

Twitch: https://twitch.tv/neurodr0me
Twitter: https://twitter.com/neurodr0me
GitHub: https://github.com/astradamus
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.practicaltools]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[26,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.practicaltools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"